### ISSUE TITLE
Add to README distinctions between this library and hashicorp/golang-lru

### ISSUE THREAD

**Issue by maggie44** [go-pkgz/expirable-cache#6]
> This cache is heavily inspired by [hashicorp/golang-lru](https://github.com/hashicorp/golang-lru) simplelru implementation.

How does it differ?

**Comment by paskal** [comment]
I've added expirable LRU to hashicorp/golang-lru in https://github.com/hashicorp/golang-lru/pull/116, I'll try to figure out what is the difference and write it to the readme.
