### ISSUE TITLE
Feature request: Add option to get expiry time

### ISSUE THREAD

**Issue by constantitus** [go-pkgz/expirable-cache#7]
I'd like to store the cache on disk when I close my application, but I need a way to get the expiry time for each item so I can store it.
I'd also need to set it back later, so having the option to set the ttl with `time.Time` would also be handy, but not as important since I can just subtract the current time.

**Comment by paskal** [comment]
What is your use case? What calculations are so costly that you want to store them in the cache but persist after the application restart?
I haven't seen that functionality in any cache I've used so far, so it's likely not something commonly expected of the cache.

**Comment by paskal** [comment]
I'll check how it can be done.

**Comment by constantitus** [comment]
> What is your use case? 

I'm storing login uuid's in a cache and I want to store them so users don't have to relogin when I restart the application. It's probably a stupid way to do things, but that's the way I thought of it.

> I haven't seen that functionality in any cache I've used so far, so it's likely not something commonly expected of the cache.

I know that storing a cache is not a common functionality and I didn't ask for it to be added, that is something I can do directly in my app. But I think a method to get the expiry time of entries in itself should not be that uncommon and that would be all I need.
